/* raptor.h - Raptor Player C FFI Header
 *
 * Usage:
 *   - Dart/Flutter: use dart:ffi to look up these symbols
 *   - C/C++: link against libraptor_ffi (libraptor.so / raptor.dll) and include this header
 */

#ifndef RAPTOR_H
#define RAPTOR_H

/* Warning: this file is autogenerated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * 不透明句柄 — Dart 侧只看到指针
 */
typedef struct RaptorHandle RaptorHandle;

/**
 * 事件回调函数类型
 */
typedef void (*RaptorEventCallback)(const char*, void*);

/**
 * 属性观察者回调函数类型
 */
typedef void (*RaptorPropertyCallback)(const char*, void*);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * 创建播放器实例
 */
struct RaptorHandle *raptor_create(void);

/**
 * 销毁播放器实例
 */
void raptor_destroy(struct RaptorHandle *handle);

/**
 * 发送命令（JSON 格式）
 */
int raptor_command(struct RaptorHandle *handle, const char *cmd_json);

/**
 * 读取属性（返回 JSON 字符串，调用者需调用 raptor_free_string 释放）
 */
char *raptor_get_property(struct RaptorHandle *handle, const char *name);

/**
 * 设置属性（JSON 格式）
 */
int raptor_set_property(struct RaptorHandle *handle, const char *name, const char *value_json);

/**
 * 订阅属性变化
 */
int64_t raptor_observe_property(struct RaptorHandle *handle,
                                const char *name,
                                void (*callback)(const char*, void*),
                                void *user_data);

/**
 * 取消属性订阅
 */
int raptor_unobserve_property(struct RaptorHandle *handle, int64_t observer_id);

/**
 * 设置事件回调
 *
 * 注意：设置回调后 `raptor_poll_event` 将不再可用（event_rx 已被回调线程接管）。
 */
void raptor_set_event_callback(struct RaptorHandle *handle,
                               void (*callback)(const char*, void*),
                               void *user_data);

/**
 * 轮询事件（非阻塞，返回 JSON 字符串或 null）
 */
char *raptor_poll_event(struct RaptorHandle *handle);

/**
 * 获取 GPU 纹理 ID（供 Flutter Texture Widget 使用）
 */
int64_t raptor_get_texture_id(struct RaptorHandle *handle);

/**
 * 设置平台原生渲染器
 */
void raptor_set_renderer(struct RaptorHandle *handle, void *renderer);

/**
 * 设置外部 Surface（Android: ANativeWindow*）
 */
int raptor_set_surface(struct RaptorHandle *handle,
                       int64_t native_window,
                       int64_t native_display,
                       uint32_t width,
                       uint32_t height);

/**
 * 分离当前 Surface（Android onPause 时调用）
 */
int raptor_detach_surface(struct RaptorHandle *handle);

/**
 * 调整 Surface 尺寸（屏幕旋转等场景）
 */
int raptor_resize_surface(struct RaptorHandle *handle, uint32_t width, uint32_t height);

/**
 * 释放由 raptor 分配的字符串
 */
void raptor_free_string(char *s);

/**
 * 获取最近的错误信息（返回 JSON 字符串或 null）
 */
char *raptor_last_error(struct RaptorHandle *handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RAPTOR_H */
